services:
  database:
    image: mysql:8
    container_name: sju-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sju-hra
    ports:
      - "3307:3306"
    volumes:
      - sju-volume:/var/lib/mysql
    networks:
      - sju-net
    restart: unless-stopped

  frontend:
    image: client:latest
    build:
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8081
        API_BASE: /sju-api
    container_name: sju-client
    ports:
      - "3000:80"
    networks:
      - sju-net
    depends_on:
      - database

  backend:
    image: server:latest
    build: 
      context: ./server
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: sju-hra
      DB_USER: root
      DB_PASS: root
    container_name: sju-server
    ports:
      - "8081:8080"
    networks:
      - sju-net
    depends_on:
      - frontend

volumes:
  sju-volume:
    external: true

networks:
  sju-net:
    external: true